<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <EmitCompilerGeneratedFiles>false</EmitCompilerGeneratedFiles>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>
    
    <ImplicitUsings>false</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Delta.Engine.Generation</RootNamespace>
    <AssemblyName>Delta.Engine.Generation</AssemblyName>
    <PackageId>Delta.Engine.Generation</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Delta.Engine.Generation.Core\Delta.Engine.Generation.Core.csproj" OutputItemType="Analyzer" PrivateAssets="all" />
  </ItemGroup>
  
</Project>
