<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Delta.Engine.Integration</RootNamespace>
    <AssemblyName>Delta.Engine.Integration</AssemblyName>
    <PackageId>Delta.Engine.Integration</PackageId>
  </PropertyGroup>

</Project>
