<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disabled</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>Delta.Engine.EditorLib</RootNamespace>
    <AssemblyName>Delta.Engine.EditorLib</AssemblyName>
    <PackageId>Delta.Engine.EditorLib</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" />
    <PackageReference Include="Silk.NET.Assimp" Version="2.20.0" />
    <PackageReference Include="Silk.NET.Shaderc" Version="2.21.0" />
    <PackageReference Include="Silk.NET.SPIRV.Cross" Version="2.20.0" />
    <PackageReference Include="Silk.NET.SPIRV.Cross.Native" Version="2.20.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Delta.Editor.Scripting\Delta.Editor.Scripting.csproj" />
    <ProjectReference Include="..\Delta.Engine.Integration\Delta.Engine.Integration.csproj" />
    <ProjectReference Include="..\Delta.Engine\Delta.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Import\Models\" />
    <Content Include="Import\Models\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Import\Shaders\" />
    <Content Include="Import\Shaders\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>


</Project>
