<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>Delta.Engine.Benchmarks</RootNamespace>
    <AssemblyName>Delta.Engine.Benchmarks</AssemblyName>
    <PackageId>Delta.Engine.Benchmarks</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Delta.Engine\Delta.Engine.csproj" />
  </ItemGroup>

</Project>
